# Generated by Django 3.1.4 on 2020-12-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentinfomodel',
            name='cvFile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
